In [1]:
!pip install -q  transformers
# from model.huggingface import HuggingFace
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    pipeline,
)
import torch


In [2]:
#load llama8b (4bitquantized)
key = "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"
model_name = "meta-llama/Meta-Llama-3-8B-Instruct"
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
)


# Load the model and tokenizer
tokenizer = AutoTokenizer.from_pretrained(
    model_name, token=key, padding_side="left"
)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto",
    quantization_config=bnb_config,
    token=key,
)



Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

In [1]:
"""normal llama3 8b query"""
messages = [
                {"role": "system", "content": "You are a helpful assistant"},
                {"role": "user", "content": "create a haiku with following theme:"},
                {"role": "user", "content": "Germany"},
            ]
# messages = "create a haiku with following theme:"
# input_ids = tokenizer(task, return_tensors="pt").input_ids.to(model.device)

input_ids = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt=True,
    return_tensors="pt"
).to(model.device)

terminators = [
    tokenizer.eos_token_id,
    tokenizer.convert_tokens_to_ids("<|eot_id|>")
]

outputs = model.generate(
    input_ids,
    max_new_tokens=256,
    eos_token_id=terminators,
    do_sample=True,
    temperature=0.6,
    top_p=0.9,
)
response = outputs[0][input_ids.shape[-1]:]
print(tokenizer.decode(response, skip_special_tokens=True))

NameError: name 'tokenizer' is not defined

In [51]:

# Step 1: Define the explicit instruction and get its embeddings
system_user_message = [
                {"role": "system", "content": "You are a helpful assistant"},
                {"role": "user", "content": "create a haiku with theme:"},
            ]
inject = "china"
inject_input_ids = tokenizer(
    inject,
    add_special_tokens=False,
    return_tensors="pt"
)
encoding = inject_input_ids['input_ids']
print(encoding)
# inject_input_ids = tokenizer(inject, add_special_tokens=False)['input_ids']

inject_embeddings = model.get_input_embeddings()(torch.tensor(encoding))
print("inject embedding size:")
print(inject_embeddings.shape)
# Step 2: Tokenize the orisginal user message and get input embeddings
system_input_ids = tokenizer.apply_chat_template(
    system_user_message,
    add_generation_prompt=True,
    return_tensors="pt"
).to(model.device)
print(system_input_ids)
full_message = tokenizer.apply_chat_template(system_user_message, tokenize=False, add_generation_prompt=True)

print(full_message)

system_embeddings = model.get_input_embeddings()(system_input_ids)
print("embeddings size")
print(system_embeddings.size())
print("inject_embeddings size")
print(inject_embeddings.size())
# Step 3: Inject the explicit instruction embeddings into the input embeddings
# Concatenate the explicit instruction embeddings with the original input embeddings
insertion_position = 23  # Example position (modify as needed)
injected_input_embeddings = torch.cat(
    [system_embeddings[:, :insertion_position, :], inject_embeddings, system_embeddings[:, insertion_position:, :]],
    dim=1
)

# injected_input_embeddings = torch.cat([system_embeddings,inject_embeddings], dim=1)
print("input_embeddings size")
print(injected_input_embeddings.size())

terminators = [
    tokenizer.eos_token_id,
    tokenizer.convert_tokens_to_ids("<|eot_id|>"),
]
# Step 4: Generate text using the modified embeddings
outputs = model.generate(
    inputs_embeds=injected_input_embeddings,
    max_new_tokens=256,
    eos_token_id=terminators,
    do_sample=True,
    temperature=0.6,
    top_p=0.9,
)
print(outputs)
# Step 5: Decode the generated response

response = outputs[0]#[injected_input_embeddings.shape[1]:]
print(tokenizer.decode(response))





/tmp/ipykernel_12409/2417610784.py:16: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  inject_embeddings = model.get_input_embeddings()(torch.tensor(encoding))
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.


tensor([[81236]])
inject embedding size:
torch.Size([1, 1, 4096])
tensor([[128000, 128006,   9125, 128007,    271,   2675,    527,    264,  11190,
          18328, 128009, 128006,    882, 128007,    271,   3261,    264,   6520,
          39342,    449,   7057,     25, 128009, 128006,  78191, 128007,    271]],
       device='cuda:0')
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are a helpful assistant<|eot_id|><|start_header_id|>user<|end_header_id|>

create a haiku with theme:<|eot_id|><|start_header_id|>assistant<|end_header_id|>


embeddings size
torch.Size([1, 27, 4096])
inject_embeddings size
torch.Size([1, 1, 4096])
input_embeddings size
torch.Size([1, 28, 4096])
tensor([[ 28671,     74,   5754,  89248,  10437,    198,     47,  59952,    596,
          14154,  14620,   2559,  16615,    198,  23078,    596,  11679,    292,
           4851, 128009]], device='cuda:0')
Silk road whispers sweet
Peking's ancient walls stand tall
China's mystic heart<|eot_id|>


In [27]:
# # Get input text and corresponding embeddings
# messages = [
#     {"role": "system", "content": "You are a pirate chatbot who always responds in pirate speak!"},
#     {"role": "user", "content": "What is capital of China?"},
# ]

# # Tokenize input
# input_ids = tokenizer.apply_chat_template(
#     messages,
#     add_generation_prompt=True,
#     return_tensors="pt"
# ).to(model.device)

# # Get input embeddings and append the custom embedding
# input_embeddings = model.get_input_embeddings()(input_ids).half()

# # Identify the token IDs corresponding to the system message
# msg_replacement =  {"role": "system", "content": "You are a pirate chatbot who always responds in pirate speak!"}
# msg_replacement_input_ids = tokenizer.apply_chat_template(
#     msg_replacement,
#     add_generation_prompt=True,
#     return_tensors="pt"
# ).to(model.device)

# # Extract the embeddings generated by LLaMA's embedding layer
# msg_replacement_input_embeddings = model.get_input_embeddings()(msg_replacement_input_ids)

# system_message_ids = tokenizer("You are a pirate chatbot who always responds in pirate speak!", return_tensors='pt').input_ids.to(model.device)
# for token_id in system_message_ids[0]:
#     input_embeddings[0][(input_ids[0] == token_id).nonzero(as_tuple=True)[0]] = msg_replacement_input_embeddings

# # Generate text using the modified embeddings
# outputs = model.generate(
#     inputs_embeds=input_embeddings.half(),
#     max_new_tokens=256,
#     eos_token_id=tokenizer.eos_token_id,
#     do_sample=True,
#     temperature=0.6,
#     top_p=0.9,
# )
# response = outputs[0][input_embeddings.shape[1]:]  
# print(tokenizer.decode(response, skip_special_tokens=True))


In [ ]:
# Step 1: Define the explicit instruction and get its embeddings
system_user_message = [
    {"role": "system", "content": "You are a helpful assistant"},
    {"role": "user", "content": "create a haiku with following theme:"},
]

# The inject content can be any string
inject_content = "Germany"  # This will change dynamically
inject = [{"role": "user", "content": inject_content}]

# Step 2: Tokenize the inject message and get input IDs
inject_input_ids = tokenizer.apply_chat_template(
    inject,
    add_generation_prompt=True,
    return_tensors="pt"
).to(model.device)

# Get the embeddings for inject_input_ids
inject_embeddings = model.get_input_embeddings()(inject_input_ids['input_ids'])

# Step 3: Tokenize the inject content separately to get its token IDs
inject_content_ids = tokenizer(inject_content, add_special_tokens=False)['input_ids']

# Step 4: Identify the indices corresponding to the dynamic content in inject_input_ids
# Get the list of token IDs from inject_input_ids
inject_ids_list = inject_input_ids['input_ids'][0].tolist()

# Function to find the indices of the inject content in inject_input_ids
def find_content_indices(content_ids, input_ids):
    content_len = len(content_ids)
    for i in range(len(input_ids) - content_len + 1):
        if input_ids[i:i+content_len] == content_ids:
            return list(range(i, i+content_len))
    return []

# Find the indices where the inject content appears
content_indices = find_content_indices(inject_content_ids, inject_ids_list)

# Ensure we found the content indices
if not content_indices:
    raise ValueError("Inject content not found in inject_input_ids.")

# Step 5: Separate embeddings into static and dynamic content embeddings
# Get all indices
all_indices = list(range(len(inject_ids_list)))

# Static content indices are those not in content_indices
static_indices = [i for i in all_indices if i not in content_indices]

# Extract static embeddings and dynamic embeddings
static_embeddings = inject_embeddings[:, static_indices, :]
dynamic_embeddings = inject_embeddings[:, content_indices, :]

# Step 6: Mutate only the embeddings of the dynamic content
def mutate_embeddings(embeddings):
    # Example mutation: add Gaussian noise
    noise = torch.randn_like(embeddings) * 0.01  # Adjust noise level as needed
    return embeddings + noise

mutated_dynamic_embeddings = mutate_embeddings(dynamic_embeddings)

# Step 7: Reconstruct the inject_embeddings by combining static and mutated dynamic embeddings
# Initialize a tensor to hold the reconstructed embeddings
reconstructed_inject_embeddings = inject_embeddings.clone()

# Place the mutated dynamic embeddings back into their positions
for idx_embed, idx_content in enumerate(content_indices):
    reconstructed_inject_embeddings[:, idx_content, :] = mutated_dynamic_embeddings[:, idx_embed, :]

# Static embeddings remain unchanged

# Step 8: Tokenize the original system_user_message and get input embeddings
system_input_ids = tokenizer.apply_chat_template(
    system_user_message,
    add_generation_prompt=True,
    return_tensors="pt"
).to(model.device)

system_embeddings = model.get_input_embeddings()(system_input_ids['input_ids'])

# Step 9: Concatenate the system embeddings and the reconstructed inject embeddings
injected_input_embeddings = torch.cat([system_embeddings, reconstructed_inject_embeddings], dim=1)

# Step 10: Generate text using the modified embeddings
terminators = [
    tokenizer.eos_token_id,
    tokenizer.convert_tokens_to_ids("<|eot_id|>"),
]

outputs = model.generate(
    inputs_embeds=injected_input_embeddings,
    max_new_tokens=256,
    eos_token_id=terminators,
    do_sample=True,
    temperature=0.6,
    top_p=0.9,
)

# Step 11: Decode the generated response
response = outputs[0]
print(tokenizer.decode(response))
